// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_prIJnyFT-FlYQHvQ4mNVW3oPG_dXiM',
    appId: '1:25944705271:web:2f3fe7940dbc04a2f9abf2',
    messagingSenderId: '25944705271',
    projectId: 'tasksync-739ef',
    authDomain: 'tasksync-739ef.firebaseapp.com',
    storageBucket: 'tasksync-739ef.appspot.com',
    measurementId: 'G-G315W20B8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC531W7Ah9PW0tP92Bkgja99QIEXyyu2EI',
    appId: '1:25944705271:android:5b82ebe36da0ed96f9abf2',
    messagingSenderId: '25944705271',
    projectId: 'tasksync-739ef',
    storageBucket: 'tasksync-739ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdlWuttrzjnYjrFPQ-OZ0V8tSx1mrb0yM',
    appId: '1:25944705271:ios:b8cb6f267da1959df9abf2',
    messagingSenderId: '25944705271',
    projectId: 'tasksync-739ef',
    storageBucket: 'tasksync-739ef.appspot.com',
    androidClientId: '25944705271-sms3uvh4vbvpuedpd07slj5ar61dolst.apps.googleusercontent.com',
    iosClientId: '25944705271-6o9bi99to98rhv1ahm0oohgilp9gbovq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdlWuttrzjnYjrFPQ-OZ0V8tSx1mrb0yM',
    appId: '1:25944705271:ios:5dcbf5b195f8756df9abf2',
    messagingSenderId: '25944705271',
    projectId: 'tasksync-739ef',
    storageBucket: 'tasksync-739ef.appspot.com',
    androidClientId: '25944705271-sms3uvh4vbvpuedpd07slj5ar61dolst.apps.googleusercontent.com',
    iosClientId: '25944705271-lnivv6cac5gf0esihrv5rm77k4aq36mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksync.RunnerTests',
  );
}
